apiVersion: v1
kind: BuildConfig
metadata:
    labels:
        app: vote-pipeline
    name: vote-pipeline
spec:
    source:
        git:
            ref: master
            uri: https://github.com/learnbyseven/cicd.git
    strategy:
        jenkinsPipelineStrategy:
            jenkinsfilePath: Jenkinsfile
        type: JenkinsPipeline
    triggers:
        - github:
            secret: S51F5dU_gnt19RQ1Z6rO
          type: GitHub
        - generic:
            secret: NpyZ9EoEs7SBDi7jMVqJ
          type: Generic
status:
  lastVersion: 0
